[window]
dynamic_padding = false
decorations = "Full"
blur = true
startup_mode = "Maximized"
opacity = 0.97
resize_increments = true
option_as_alt = "Both"

[font]
normal.family = "SF Mono"
normal.style = "Regular"
bold.family = "SF Mono"
bold.style = "Semibold"
italic.family = "SF Mono"
italic.style = "Regular Italic"
size = 12

[colors]
primary.background = '0x453652'

[cursor]
style.blinking = "On"
blink_interval = 900
blink_timeout = 15
unfocused_hollow = false

[mouse]
hide_when_typing = true

[shell]
program = "/usr/local/bin/tmux"

[keyboard]
bindings = [
	{ key = "Right", mods = "Alt", chars = "\u001BF"  },
	{ key = "Left",  mods = "Alt", chars = "\u001BB"  },
]
