# Custom Prompt
autoload -Uz vcs_info
precmd() {
	vcs_info
}

zstyle ':vcs_info:git:*' formats '[%b] '
setopt PROMPT_SUBST
PROMPT='%F{cyan}[%D{%I:%M%p}]%f %F{magenta}%n%f %F{red}${vcs_info_msg_0_}%f%F{blue}%~%f %F{blue}%(!.#.$)%f '


# History
HISTFILE=~/.zsh_history
HISTSIZE=500000
SAVEHIST=500000
setopt appendhistory
setopt INC_APPEND_HISTORY  
setopt SHARE_HISTORY


# Colors
export CLICOLOR=1
export LESS="--RAW-CONTROL-CHARS"
source ~/.LESS_TERMCAP


# OS-based stuff
case `uname` in 
    Darwin)
        alias python3=/opt/homebrew/bin/python3
        alias python=/opt/homebrew/bin/python3
		eval $(/opt/homebrew/bin/brew shellenv)
        export PATH=$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH
    ;;
    Linux)
		alias bat="batcat"
    ;;
esac


# Aliases
alias rm='rm -i'
alias gdb='gdb -silent'
alias ls='ls --color=auto'
alias grep='grep --color=auto'

alias reload='exec zsh'

alias ll='ls -AlF'
alias la='ls -A'
alias l='ls -CF'

# https://www.reddit.com/r/dotfiles/comments/13nnmia/when_youre_too_used_to_vim/
alias :q='exit'
alias :w="echo 'not in vim :)'"

alias whitenoise='mpv --no-video ~/Videos/white_noise.mp4'

alias cls='clear;ls'

function cdl {
	cd $1
	ls --color=auto
}

# Plugins
DOTFILEDIR="$(< ~/.dotfiledir)"

for file in $DOTFILEDIR/plugins/zsh/*(.); do
	source "$file"
done

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=5'

# Other
export SHELL=/bin/zsh
fastfetch -c paleofetch
source $DOTFILEDIR/plugins/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
