# Custom Prompt
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '[%b] '
setopt PROMPT_SUBST
PROMPT='%F{cyan}[%D{%I:%M%p}]%f %F{magenta}%n%f %F{red}${vcs_info_msg_0_}%f%F{blue}%~%f %F{blue}%(!.#.$)%f '


# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory


# Colors
export CLICOLOR=1
export LESS="--RAW-CONTROL-CHARS"
source ~/.LESS_TERMCAP


# OS-based stuff
case `uname` in 
    Darwin)
        alias python3=/opt/homebrew/bin/python3
        alias python=/opt/homebrew/bin/python3
		eval $(/opt/homebrew/bin/brew shellenv)
        export PATH=$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH
    ;;
    Linux)
		alias bat="batcat"
    ;;
esac


# Aliases
alias rm='rm -i'
alias gdb='gdb -silent'
alias ls='ls --color=auto'
alias grep='grep --color=auto'

alias reload='exec zsh'

alias ll='ls -AlF'
alias la='ls -A'
alias l='ls -CF'

alias cls='clear;ls'

function cdl {
	cd $1
	ls --color=auto
}

# Plugins
DOTFILEDIR="$(< ~/.dotfiledir)"

for file in $DOTFILEDIR/plugins/zsh/*(.); do
	source "$file"
done

neofetch
source $DOTFILEDIR/plugins/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
